# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('at_name', models.AutoField(primary_key=True, serialize=False)),
                ('at_category', models.TextField()),
                ('at_description', models.TextField()),
            ],
        ),
    ]
