# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='at_url',
            field=models.TextField(null=True),
        ),
    ]
